'use strict';
const {sources,entries}=globalThis.P7_CONTENT;
const {filterEntries,readBookmarks}=globalThis.P7Core;
const $=s=>document.querySelector(s);
const key=APP_CONFIG.storageId+':'+new URL('./',location.href).pathname;
let saved=[],readable=true,view='library',lastHash='',lastScroll=0;
const el=(tag,text,className)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;};
function announce(t){$('#status').textContent=t;}
function refreshSaved(){try{saved=readBookmarks(localStorage,key,entries);readable=true;}catch{readable=false;announce('Bookmarks could not be read. Existing data has not been changed. Reading still works.');}}
function bookmark(e){const b=el('button',saved.includes(e.id)?'Saved':'Save','bookmark');b.type='button';b.setAttribute('aria-label','Bookmark '+e.title);b.setAttribute('aria-pressed',String(saved.includes(e.id)));b.disabled=!readable;b.onclick=()=>{refreshSaved();if(!readable)return;const next=saved.includes(e.id)?saved.filter(id=>id!==e.id):[...saved,e.id];try{localStorage.setItem(key,JSON.stringify(next));saved=next;announce(saved.includes(e.id)?'Bookmark saved.':'Bookmark removed.');document.querySelectorAll('[data-bookmark]').forEach(button=>{const yes=saved.includes(button.dataset.bookmark);button.textContent=yes?'Saved':'Save';button.setAttribute('aria-pressed',String(yes));});if(view==='saved'&&!$('#browse').hidden)renderList();}catch{announce('Could not save this bookmark. Browser storage may be full or blocked.');}};b.dataset.bookmark=e.id;return b;}
function prose(text,target){const lines=text.split('\n');let paragraph=[];const flush=()=>{if(paragraph.length){target.append(el('p',paragraph.join('\n').replace(/\*\*/g,'')));paragraph=[];}};for(const line of lines){if(line.startsWith('## ')){flush();target.append(el('h2',line.slice(3)));}else if(line.startsWith('# ')){flush();}else if(line.startsWith('- ')){flush();target.append(el('p','• '+line.slice(2)));}else if(!line.trim()){flush();}else paragraph.push(line);}flush();}
function renderList(){const found=filterEntries(entries,{query:$('#search').value,view,section:$('#section').value,saved});$('#entries').replaceChildren();$('#count').textContent=found.length+' '+(found.length===1?'entry':'entries');$('#empty').hidden=found.length>0;$('#empty').textContent=view==='saved'&&!saved.length?'No bookmarks yet. Save an entry to return to it here.':'No matches. Try another word or choose all sections.';$('#clear').hidden=!$('#search').value;for(const e of found){const card=el('article',undefined,'card'),top=el('div',undefined,'card-top');top.append(el('span',e.category,'type'),bookmark(e));const h=el('h2'),a=el('a',e.title);a.href='#entry/'+e.id;a.onclick=()=>{lastHash=location.hash;lastScroll=scrollY;};h.append(a);const plain=e.body.replace(/\*\*/g,'').replace(/\n/g,' ');const summary=plain.length>180?plain.slice(0,177)+'…':plain;card.append(top,h,el('p',summary));if(e.tags.length){const tags=el('div',undefined,'tags');for(const t of e.tags.slice(0,4))tags.append(el('span',t,'tag'));card.append(tags);}$('#entries').append(card);}}
function openReader(entry,sourceIndex){const r=$('#reader');r.replaceChildren();const back=el('button','Back to library');back.onclick=()=>{location.hash=lastHash;requestAnimationFrame(()=>window.scrollTo(0,lastScroll));};const toolbar=el('div',undefined,'toolbar');toolbar.append(back);if(entry)toolbar.append(bookmark(entry));r.append(toolbar);const source=sources[entry?entry.source:sourceIndex];r.append(el('p',entry?entry.category:'Project source','eyebrow'));r.append(el('h1',entry?entry.title:source.title));r.append(el('p',source.status,'reader-meta'));prose(entry?entry.body:source.text,r);if(entry){const a=el('a','Read source: '+source.title,'source-link');a.href='#source/'+entry.source;r.append(a);const related=entries.filter(e=>e.id!==entry.id&&e.tags.some(t=>entry.tags.includes(t))).map(e=>({e,score:e.tags.filter(t=>entry.tags.includes(t)).length})).sort((a,b)=>b.score-a.score).slice(0,4);if(related.length){r.append(el('h2','Related reading'));const list=el('ul');for(const {e} of related){const li=el('li'),a=el('a',e.title);a.href='#entry/'+e.id;li.append(a);list.append(li);}r.append(list);}}else{r.append(el('p',source.name+' · Version '+source.version+' · 7 October 2026','reader-meta'));}$('#browse').hidden=true;r.hidden=false;document.title=(entry?entry.title:source.title)+' · Perfume 7';r.focus();window.scrollTo(0,0);}
function route(){const hash=location.hash.slice(1);if(hash.startsWith('entry/')){const e=entries.find(e=>e.id===hash.slice(6));if(e){openReader(e);return;}announce('That entry could not be found.');}if(hash.startsWith('source/')){const i=Number(hash.slice(7));if(Number.isInteger(i)&&sources[i]){openReader(null,i);return;}announce('That source could not be found.');}const next=hash.startsWith('view/')?hash.slice(5):'library';if(view!==next){$('#search').value='';$('#section').value='';}view=['library','materials','research','saved'].includes(next)?next:'library';$('#browse').hidden=false;$('#reader').hidden=true;$('#page-title').textContent={library:'The library.',materials:'Materials & accords.',research:'Research & thought.',saved:'Saved reading.'}[view];document.title='PERFUME 7';document.querySelectorAll('[data-view]').forEach(a=>{if(a.dataset.view===view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});const selectedSection=$('#section').value;$('#section').replaceChildren(new Option('All sections',''));sources.forEach((s,i)=>{if(view==='materials'&&i!==2||view==='research'&&[1,2].includes(i))return;$('#section').add(new Option(s.title,String(i)));});$('#section').value=selectedSection;renderList();}
$('#search').addEventListener('input',renderList);$('#section').addEventListener('change',renderList);$('#clear').onclick=()=>{$('#search').value='';renderList();$('#search').focus();};window.addEventListener('hashchange',route);window.addEventListener('storage',event=>{if(event.key===key||event.key===null){refreshSaved();route();}});refreshSaved();route();
if('serviceWorker' in navigator&&['https:','http:'].includes(location.protocol)){
 navigator.serviceWorker.register('./sw.js').then(reg=>{const update=()=>{if(reg.waiting)$('#offline').textContent='A library update is ready. Close all Perfume 7 tabs and reopen to load it.';};update();reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed')update();if(worker.state==='redundant')$('#offline').textContent='Offline download failed. Reconnect and reload to retry.';});});return navigator.serviceWorker.ready;}).then(()=>{if(!$('#offline').textContent.includes('update'))$('#offline').textContent='Library available offline.';}).catch(()=>{$('#offline').textContent='Offline reading is unavailable. Keep an internet connection to reopen.';});
}else $('#offline').textContent='Offline reading requires HTTPS or a local server.';
