'use strict';
const C=UsualCore,settings=APP_CONFIG,$=id=>document.getElementById(id);
$('app-name').textContent=settings.name;
for(const [key,value] of Object.entries(settings.colors))document.documentElement.style.setProperty('--'+key,value);
let db,records=[],editing=null,photo=null,lastDeleted=null,busy=false,photoPending=false,photoGeneration=0;
let baseline='',previewURL=null,cardURLs=[];
const channel=typeof BroadcastChannel === 'function' ? new BroadcastChannel(settings.storageId+':'+new URL('./',location.href).pathname) : null;
function announce(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
function fields(){return Object.fromEntries(C.fields.map(k=>[k,$(k).value]));}
function snapshot(){return JSON.stringify({...fields(),favorite:$('favorite').checked,photoGeneration});}
function dirty(){return snapshot()!==baseline;}
function update(){for(const id of [...C.fields,'favorite','photo','camera','remove-photo','cancel','add','undo'])$(id).disabled=busy||photoPending;const count=C.words(fields());$('word-count').textContent=count+'/45 words';$('word-count').classList.toggle('over',count>45);const duplicates=records.filter(r=>r.id!==editing&&C.normalize(r.name)===C.normalize($('name').value));$('duplicate').hidden=!duplicates.length;$('duplicate').textContent='This name already exists. Check the existing customer before saving another.';$('save').disabled=!db||busy||photoPending;}
function setBusy(value){busy=value;update();$('export').disabled=!db||busy;$('import-button').disabled=!db||busy;}
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(settings.storageId+':'+new URL('./',location.href).pathname,1);req.onupgradeneeded=()=>req.result.createObjectStore('customers',{keyPath:'id'});req.onsuccess=()=>{req.result.onversionchange=()=>{req.result.close();db=null;setBusy(false);announce('Storage changed in another window. Reload before saving.',true);};resolve(req.result);};req.onerror=()=>reject(req.error);req.onblocked=()=>announce('Close other app windows so storage can open.',true);});}
function transaction(mode,operation){return new Promise((resolve,reject)=>{const tx=db.transaction('customers',mode),store=tx.objectStore('customers');let value;tx.oncomplete=()=>resolve(value);tx.onabort=()=>reject(tx.error||Error('Storage write failed.'));tx.onerror=()=>{};try{operation(store,tx,result=>{value=result;});}catch(error){tx.abort();reject(error);}});}
async function refresh(){records=await transaction('readonly',(store,tx,done)=>{const request=store.getAll();request.onsuccess=()=>done(request.result);});for(const record of records){C.validate(record);if(record.photo!==null&&(!(record.photo instanceof Blob)||record.photo.type!=='image/jpeg'||record.photo.size>30000))throw Error('Invalid stored photo.');}render();update();}
function broadcast(){channel?.postMessage('changed');}
function button(label,action){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=action;return b;}
function text(tag,value,className){const e=document.createElement(tag);e.textContent=value;if(className)e.className=className;return e;}
function render(){cardURLs.forEach(URL.revokeObjectURL);cardURLs=[];$('entries').replaceChildren();const matches=C.search(records,$('search').value);$('results').textContent=matches.length+' of '+records.length+' customers';$('empty').hidden=matches.length>0;$('empty').textContent=records.length?'No matches. Clear search or add a customer.':settings.emptyMessage;for(const r of matches){const li=document.createElement('li');li.className='card';const identity=document.createElement('div');identity.className='identity';if(r.photo){const img=document.createElement('img');img.className='thumb';img.alt='Photo of '+r.name;img.src=URL.createObjectURL(r.photo);cardURLs.push(img.src);identity.append(img);}const person=document.createElement('div');person.className='person';person.append(text('h3',r.name),text('p',[r.cue1,r.cue2].filter(Boolean).join(' · '),'cues'),text('p',r.drink,'drink'));identity.append(person);const actions=document.createElement('div');actions.className='card-actions';const star=button(r.favorite?'★ Favorite':'☆ Favorite',()=>changeFavorite(r.id));star.setAttribute('aria-pressed',String(r.favorite));star.setAttribute('aria-label',(r.favorite?'Unfavorite ':'Favorite ')+r.name);actions.append(star,button('Edit',()=>edit(r.id)),button('Delete',()=>remove(r.id)));li.append(identity);if(r.note1||r.note2){const notes=document.createElement('details');notes.className='notes';notes.append(text('summary','Notes'));for(const n of [r.note1,r.note2].filter(Boolean))notes.append(text('p',n));li.append(notes);}li.append(actions);$('entries').append(li);}}
function showPhoto(){if(previewURL)URL.revokeObjectURL(previewURL);previewURL=photo?URL.createObjectURL(photo):null;$('photo-preview').hidden=!photo;$('remove-photo').hidden=!photo;if(photo)$('photo-preview').src=previewURL;else $('photo-preview').removeAttribute('src');}
function reset(clear=true){editing=null;if(clear){for(const key of C.fields)$(key).value='';photo=null;$('favorite').checked=false;photoGeneration++;}$('photo').value='';$('camera').value='';$('save').textContent=settings.saveLabel;$('editor-heading').textContent='Add a customer';showPhoto();baseline=clear?snapshot():'';update();}
function openEditor(){ $('editor').open=true;$('name').focus();$('editor').scrollIntoView({block:'start',behavior:'smooth'});}
function edit(id){if(busy||photoPending)return;if(editing===id){openEditor();return;}if(dirty()&&!confirm('Replace your unsaved customer draft?'))return;const r=records.find(x=>x.id===id);if(!r)return;editing=id;for(const key of C.fields)$(key).value=r[key];photo=r.photo;$('favorite').checked=r.favorite;photoGeneration++;showPhoto();baseline=snapshot();$('save').textContent='SAVE CHANGES';$('editor-heading').textContent='Edit '+r.name;update();openEditor();}
async function write(action,message){if(busy||!db||photoPending)return;setBusy(true);try{await action();broadcast();await refresh();announce(message);}catch(error){announce(error.message+' Check browser storage before retrying.',true);}finally{setBusy(false);}}
async function changeFavorite(id){await write(()=>transaction('readwrite',(store)=>{const req=store.get(id);req.onsuccess=()=>{if(req.result)store.put({...req.result,favorite:!req.result.favorite});};}),'Favorite updated.');}
async function remove(id){if(busy||photoPending||!confirm('Delete this customer? You can undo until the next deletion or reload.'))return;await write(async()=>{const deleted=await transaction('readwrite',(store,tx,done)=>{const req=store.get(id);req.onsuccess=()=>{if(req.result){done(req.result);store.delete(id);}};});if(!deleted)throw Error('This customer was already deleted.');lastDeleted=deleted;$('undo-area').hidden=false;if(editing===id)reset(false);},'Customer deleted. Any open draft is still here.');}
$('undo').onclick=()=>write(async()=>{if(!lastDeleted)return;const r=lastDeleted;await transaction('readwrite',(store,tx)=>{const req=store.get(r.id);req.onsuccess=()=>{if(req.result)tx.abort();else store.add(r);};});lastDeleted=null;$('undo-area').hidden=true;},'Customer restored.');
$('capture').onsubmit=async event=>{event.preventDefault();if(busy||photoPending||!db)return;const r={...fields(),id:editing||crypto.randomUUID(),favorite:$('favorite').checked,createdAt:Date.now(),photo};for(const k of C.fields)r[k]=r[k].trim();try{C.validate(r);}catch(error){announce(error.message,true);return;}if(records.some(x=>x.id!==editing&&C.normalize(x.name)===C.normalize(r.name))&&!confirm('A customer with this name exists. Save this record anyway?'))return;await write(async()=>{await transaction('readwrite',(store,tx)=>{if(!editing){store.add(r);return;}const req=store.get(editing);req.onsuccess=()=>{if(!req.result){tx.abort();return;}store.put({...r,createdAt:req.result.createdAt});};});reset();$('editor').open=false;},'Customer saved.');};
$('add').onclick=()=>{if(busy||photoPending)return;if(dirty()&&!confirm('Discard your unsaved draft and add a new customer?'))return;reset();openEditor();};
$('cancel').onclick=()=>{if(busy||photoPending)return;if(dirty()&&!confirm('Discard your unsaved changes?'))return;reset();$('editor').open=false;announce('Canceled.');};
for(const key of C.fields)$(key).addEventListener('input',update);$('favorite').onchange=update;
$('search').oninput=render;$('clear-search').onclick=()=>{$('search').value='';render();$('search').focus();};
function loadImage(blob){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(blob);img.onload=()=>{URL.revokeObjectURL(url);resolve(img);};img.onerror=()=>{URL.revokeObjectURL(url);reject(Error('This image cannot be opened. Choose a JPEG or PNG.'));};img.src=url;});}
function encode(canvas,quality){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(Error('Could not compress this photo.')),'image/jpeg',quality));}
async function compress(file){const image=await loadImage(file),canvas=document.createElement('canvas');let size=320;while(size>=80){const scale=Math.min(1,size/Math.max(image.naturalWidth,image.naturalHeight));canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);for(const quality of [.65,.5,.35]){const blob=await encode(canvas,quality);if(blob.size<=30000)return blob;}size=Math.floor(size*.75);}throw Error('Photo could not fit. Choose a simpler image.');}
async function selectPhoto(event){const file=event.target.files[0];if(!file)return;if(busy||photoPending){event.target.value='';return;}photoPending=true;update();try{const next=await compress(file);photo=next;photoGeneration++;showPhoto();announce('Photo ready. Save the customer to keep it.');}catch(error){announce(error.message,true);}finally{photoPending=false;event.target.value='';update();}}
$('photo').onchange=selectPhoto;$('camera').onchange=selectPhoto;$('remove-photo').onclick=()=>{if(busy||photoPending)return;photo=null;photoGeneration++;showPhoto();update();};
function dataURL(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob);});}
$('export').onclick=()=>write(async()=>{const customers=await transaction('readonly',(store,tx,done)=>{const req=store.getAll();req.onsuccess=()=>done(req.result);});const output=await Promise.all(customers.map(async r=>({...r,photo:r.photo?await dataURL(r.photo):null})));const blob=new Blob([JSON.stringify({app:'the-usual',version:1,customers:output})],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='the-usual-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);},'Backup download requested. Keep the file to restore customers and photos.');
$('import-button').onclick=()=>{if(!busy)$('import').click();};
$('import').onchange=async event=>{const file=event.target.files[0];event.target.value='';if(!file||busy||photoPending)return;setBusy(true);try{const incoming=C.validateBackup(JSON.parse(await file.text()));for(const r of incoming){if(r.photo){const bytes=atob(r.photo.split(',')[1]);if(bytes.length>30000)throw Error('Backup photo exceeds 30 KB.');r.photo=new Blob([Uint8Array.from(bytes,c=>c.charCodeAt(0))],{type:'image/jpeg'});const image=await loadImage(r.photo);if(Math.max(image.naturalWidth,image.naturalHeight)>320)throw Error('Backup photo exceeds 320 pixels.');}}
await refresh();const conflicts=incoming.filter(r=>records.some(x=>x.id===r.id)).length;if(!confirm('Import '+incoming.length+' customers? '+conflicts+' matching records will be replaced. Other customers and your open draft stay.'))return;
await transaction('readwrite',store=>incoming.forEach(r=>store.put(r)));broadcast();await refresh();announce('Imported '+incoming.length+' customers.');}catch(error){announce('Import failed: '+error.message+' Existing records and draft have been kept.',true);}finally{setBusy(false);}};
channel?.addEventListener('message',()=>{if(!busy)refresh().catch(error=>announce(error.message,true));});
window.addEventListener('beforeunload',event=>{if(dirty()||photoPending){event.preventDefault();event.returnValue='';}});
reset();openDB().then(async connection=>{db=connection;try{await refresh();setBusy(false);}catch(error){db.close();db=null;setBusy(false);announce('Could not open customers: '+error.message,true);}}).catch(error=>announce('Could not open browser storage. '+error.message,true));
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>announce('Offline files could not be cached. Customer storage still works.',true));
