const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const C=require('../core.js');
const base={id:'1',name:'José',cue1:'silver glasses',cue2:'crescent tattoo',drink:'tequila soda',note1:'quiet greeting',note2:'',favorite:false,createdAt:1,photo:null};
assert.equal(C.words(base),9);
assert.equal(C.search([base],' JOSE   SILVER tequila ').length,1);
assert.equal(C.search([base],'silver vodka').length,0);
assert.equal(C.search([base],'soda tequila').length,1);
assert.equal(C.search([base],'quiet').length,1);
assert.equal(C.search([base],'').length,1);
const other={...base,id:'2',name:'Jo',favorite:true};
assert.equal(C.search([base,other],'jo')[0].id,'2');
assert.equal(C.search([base,other],'')[0].id,'2');
assert.equal(C.search([base,{...other,name:'José',favorite:true}],'jose')[0].id,'2');
assert.doesNotThrow(()=>C.validate({...base,name:'n',cue1:'',cue2:'',drink:Array(44).fill('word').join(' '),note1:''}));
assert.throws(()=>C.validate({...base,name:'n',cue1:'',cue2:'',drink:Array(45).fill('word').join(' '),note1:''}),/45 words/);
assert.throws(()=>C.validate({...base,name:' '}),/name/);
assert.throws(()=>C.validate({...base,createdAt:1e20}),/Invalid customer/);
const backup={app:'the-usual',version:1,customers:[base]};
assert.deepEqual(C.validateBackup(backup),[base]);
assert.throws(()=>C.validateBackup({...backup,version:2}),/backup/);
assert.throws(()=>C.validateBackup({...backup,customers:[base,base]}),/duplicate/);
assert.throws(()=>C.validateBackup({...backup,customers:[{...base,photo:'data:text/html;base64,AAAA'}]}),/photo/);
const root=path.resolve(__dirname,'..'),manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest')));
assert.equal(manifest.name,'THE USUAL');assert.equal(manifest.start_url,'./');
for(const icon of manifest.icons)assert.ok(fs.existsSync(path.join(root,icon.src)));
for(const f of ['core.js','config.js','script.js','style.css'])assert.ok(fs.readFileSync(path.join(root,'sw.js'),'utf8').includes("'./"+f+"'"));
console.log('PASS: multi-field search, accent and whitespace normalization, all-word matching, rankings, 45-word boundary, required name, invalid dates, backup validation, duplicate IDs, metadata and offline assets.');
